---
title: "Part 1 Data Preprocessing"
output: html_notebook
---

## 1.1 Importing
```{r}
# Importing the dataset
dataset = read.csv('Data.csv')
head(dataset)
```

## 1.2 Missing Data
```{r}
# Taking care of missing data
dataset$Age = ifelse(is.na(dataset$Age), 
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)), 
                     dataset$Age)
dataset$Salary = ifelse(is.na(dataset$Salary), 
                     ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)), 
                     dataset$Salary)
head(dataset)
```

## 1.3 Categorical Data
```{r}
# Encoding categorical data. This is non-order related. 
dataset$Country = factor(dataset$Country, 
                         levels = c('France', 'Spain', 'Germany'), 
                         labels = c(1, 2, 3))
dataset$Purchased = factor(dataset$Purchased, 
                         levels = c('No', 'Yes'), 
                         labels = c(0, 1))
head(dataset)
```

## 1.4 Splitting
```{r}
# Split the dateset into the train set and test set
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)
head(training_set)
```

```{r}
head(test_set)
```

## 1.5 Feature Scaling
There are two types of feature scaling:

- **Standardization**:

$$x_{\text{stand}}=\frac{x-\text{mean}(x)}{\text{standard deviation}(x)}$$

- **Normalization**:

$$x_{\text{norm}}=\frac{x-\min(x)}{\max(x)-\min(x)}$$


```{r}
# Feature scaling
training_set[, 2:3] = scale(training_set[, 2:3])
test_set[, 2:3] = scale(test_set[, 2:3])
head(training_set)
```

```{r}
head(test_set)
```